apiVersion: v1
kind: Pod
metadata:
  name: debug
  labels:
    app: debug
spec:
  containers:
  - name: debug
    image: python:3.11-slim
    command: ["sleep", "infinity"]
    # kubectl expose pod debug --type=LoadBalancer --name=debug-svc --port=8000 --target-port=5000
